#! /bin/bash
#
# Usage: Rofi "configs" script
#
# Joris van Dijk | gitlab.com/jorisvandijk 
#
# Original by:  Derek Taylor
#               Simon Ingelsson
#               HostGrady
#
#     Published under GPL-3.0-or-later

# terminal
TERM=termite

# Options
declare -A options
options[bash]="$HOME/.bashrc"
options[dunst]="$HOME/.config/dunst/dunstrc"
options[gtk]="$HOME/.config/gtk-3.0/settings.ini"
options[i3]="$HOME/.config/i3/config"
options[i3 status]="$HOME/.config/i3status/config"
options[micro]="$HOME/.config/micro/settings.json"
options[neomutt]="$HOME/.config/neomutt/neomuttrc"
options[neovim]="$HOME/.config/nvim/init.vim"
options[picom]="$HOME/.config/picom/picom.conf"
options[rofi]="$HOME/.config/rofi/config.rasi"
options[termite]="$HOME/.config/termite/config"

# Clean options array making sure that the files exist
declare -A options_clean
  for i in "${!options[@]}"; do
    [[ -f ${options["${i}"]} ]] && options_clean["${i}"]=${options["${i}"]}
  done

choice=$(printf '%s\n' "${!options_clean[@]}" | sort | rofi -dmenu -i -l 20 -p 'Edit config:' "$@")

# What to do when/if we choose a file to edit.
if [ "$choice" ]; then
  cfg=$(printf '%s\n' "${options_clean["${choice}"]}")
  $TERM -e "micro $cfg"
else
    exit 0
fi
